version: '3.9'
services:
  docker-monitor:
    image: javidev99/docker-monitor-helper:latest
    container_name: docker-monitor-helper
    restart: unless-stopped
    ports:
      - 7676:7676
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./state:/app/state
    environment:
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: user_to_send_notifications@gmail.com
      SMTP_PASS: // password app to use SMTP_USER account to send notifications
      EMAIL_FROM: // same as SMTP_USER
      EMAIL_TO: // who is going to receive the notification
